<?php
$config=array(
	"general"=>array(
	),
	"db"=>array(
		"host"=>DB_HOST,
		"user"=>DB_USER,
		"password"=>DB_PASSW,
		"base"=>DB_BASE,
		"forms"=>array(
			"personales"=>array(
				"id_personales"=>null,
				"nombre"=>"",
				"apaterno"=>"",
				"amaterno"=>"",
				"fecha_nacimiento"=>"",
				"nacionalidad"=>"",
				"estado_civil"=>"",
				"codigo_postal"=>"",
				"telefono"=>"",
				"email"=>""
			),
			"escolaridad"=>array(
				"id_escolaridad"=>null,
				"nombre_escuela"=>"",
				"fecha_inicio"=>"",
				"fecha_fin"=>"",
				"nivel"=>""
			),
			"experiencia"=>array(
				"id_experiencia"=>null,
				"nombre_empresa"=>"",
				"fecha_inicio"=>"",
				"fecha_fin"=>"",
				"puesto"=>"",
				"funciones"=>""
			),
			"idiomas"=>array(
				"id_idioma"=>null,
				"idioma"=>"",
				"dominio"=>"",
				"certificado"=>""
			),
			"herramientas"=>array(
				"id_herramienta"=>null,
				"nombre_herramienta"=>"",
				"descripcion"=>"",
				"dominio"=>""
			)
		)
	)
);
?>
